In [71]:
import torch
import numpy
import os

In [72]:
# epochs_list = [34, 35, 36, 37]
# epochs_list = list(range(40,60))
epochs_list = list(range(10))

# no BN: /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/multiruns/autoencoder_balls_encoded_128/2023-10-05_13-50-15/model.hinge_loss_weight=0.0,model.mmd_loss.fix_sigma=null,model.mmd_loss.kernel_multiplier=1.0,model.mmd_loss.kernel_number=3,model.penalty_weight=10.0,model.save_encoded_data=True,model.z_dim_invariant_fraction=0.8,model/autoencoder=mlp_ae_balls,model=balls_md_encoded_autoencoder/
path_header = "/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/multiruns/autoencoder_balls_encoded_128/2023-10-05_16-09-57/model.hinge_loss_weight=0.0,model.penalty_weight=1.0,model.save_encoded_data=True,model.z_dim_invariant_fraction=0.8,model/autoencoder=mlp_ae_balls,model=balls_md_encoded_autoencoder/"

train_dataset_list = []
valid_dataset_list = []

for epoch in epochs_list:
    train_dataset_list.append(torch.load(os.path.join(path_header, f"double_encoded_img_balls_encoded_train_epoch_{epoch}.pt")))
    valid_dataset_list.append(torch.load(os.path.join(path_header, f"double_encoded_img_balls_encoded_valid_epoch_{epoch}.pt")))


In [73]:
from sklearn.linear_model import LinearRegression


z_dim_invariant = 102

for i, train_dataset in enumerate(train_dataset_list):
    print(f"================================================================================================")
    z_hat = train_dataset["z_hat"]
    z_hat_inv = train_dataset["z_hat"][:, :z_dim_invariant]
    z_inv = train_dataset["z_invariant"]
    z_spu = train_dataset["z_spurious"]
    z = train_dataset["z"]

    print(f"z_hat.shape: {z_hat.shape}, z_hat_inv.shape: {z_hat_inv.shape}, z_inv.shape: {z_inv.shape}, z_spu.shape: {z_spu.shape}, z.shape: {z.shape}")

    reg = LinearRegression().fit(z_hat, z)
    r2 = reg.score(z_hat, z)
    print(f"R2 score for z_hat predicting z: {r2}")
    reg = LinearRegression().fit(z, z_hat)
    r2 = reg.score(z, z_hat)
    print(f"R2 score for z predicting z_hat: {r2}")

    reg = LinearRegression().fit(z_hat_inv, z_inv)
    r2 = reg.score(z_hat_inv, z_inv)
    print(f"R2 score for z_hat_inv predicting z_inv: {r2}")

    reg = LinearRegression().fit(z_hat_inv, z_spu)
    r2 = reg.score(z_hat_inv, z_spu)
    print(f"R2 score for z_hat_inv predicting z_spu: {r2}")

    reg = LinearRegression().fit(z_inv, z_hat_inv)
    r2 = reg.score(z_inv, z_hat_inv)
    print(f"R2 score for z_inv predicting z_hat_inv: {r2}")

    reg = LinearRegression().fit(z_spu, z_hat_inv)
    r2 = reg.score(z_spu, z_hat_inv)
    print(f"R2 score for z_spu predicting z_hat_inv: {r2}")


z_hat.shape: torch.Size([50000, 128]), z_hat_inv.shape: torch.Size([50000, 102]), z_inv.shape: torch.Size([50000, 2]), z_spu.shape: torch.Size([50000, 2]), z.shape: torch.Size([50000, 4])
R2 score for z_hat predicting z: 0.8979508868759722
R2 score for z predicting z_hat: 0.14294958158856697
R2 score for z_hat_inv predicting z_inv: 0.6747265187157855
R2 score for z_hat_inv predicting z_spu: 0.2960960992955896
R2 score for z_inv predicting z_hat_inv: 0.0399106943479328
R2 score for z_spu predicting z_hat_inv: 0.006208454614209337
z_hat.shape: torch.Size([50000, 128]), z_hat_inv.shape: torch.Size([50000, 102]), z_inv.shape: torch.Size([50000, 2]), z_spu.shape: torch.Size([50000, 2]), z.shape: torch.Size([50000, 4])
R2 score for z_hat predicting z: 0.8991790504388104
R2 score for z predicting z_hat: 0.1430471276832015
R2 score for z_hat_inv predicting z_inv: 0.6416862404049652
R2 score for z_hat_inv predicting z_spu: 0.17420769351173965
R2 score for z_inv predicting z_hat_inv: 0.023726646

In [74]:
for i, valid_dataset in enumerate(valid_dataset_list):
    print(f"================================================================================================")
    z_hat = valid_dataset["z_hat"]
    z_hat_inv = valid_dataset["z_hat"][:, :z_dim_invariant]
    z_inv = valid_dataset["z_invariant"]
    z_spu = valid_dataset["z_spurious"]
    z = valid_dataset["z"]

    print(f"z_hat.shape: {z_hat.shape}, z_hat_inv.shape: {z_hat_inv.shape}, z_inv.shape: {z_inv.shape}, z_spu.shape: {z_spu.shape}, z.shape: {z.shape}")
    print(f"z_hat.mean(): {z_hat.mean()}, z_hat.std: {z_hat.std()}")

    reg = LinearRegression().fit(z_hat, z)
    r2 = reg.score(z_hat, z)
    print(f"R2 score for z_hat predicting z: {r2}")
    reg = LinearRegression().fit(z, z_hat)
    r2 = reg.score(z, z_hat)
    print(f"R2 score for z predicting z_hat: {r2}")

    reg = LinearRegression().fit(z_hat_inv, z_inv)
    r2 = reg.score(z_hat_inv, z_inv)
    print(f"R2 score for z_hat_inv predicting z_inv: {r2}")

    reg = LinearRegression().fit(z_hat_inv, z_spu)
    r2 = reg.score(z_hat_inv, z_spu)
    print(f"R2 score for z_hat_inv predicting z_spu: {r2}")

    reg = LinearRegression().fit(z_inv, z_hat_inv)
    r2 = reg.score(z_inv, z_hat_inv)
    print(f"R2 score for z_inv predicting z_hat_inv: {r2}")

    reg = LinearRegression().fit(z_spu, z_hat_inv)
    r2 = reg.score(z_spu, z_hat_inv)
    print(f"R2 score for z_spu predicting z_hat_inv: {r2}")


z_hat.shape: torch.Size([10000, 128]), z_hat_inv.shape: torch.Size([10000, 102]), z_inv.shape: torch.Size([10000, 2]), z_spu.shape: torch.Size([10000, 2]), z.shape: torch.Size([10000, 4])
z_hat.mean(): 0.0024542210157960653, z_hat.std: 0.28953051567077637
R2 score for z_hat predicting z: 0.9465012822042678
R2 score for z predicting z_hat: 0.25186805790619504
R2 score for z_hat_inv predicting z_inv: 0.938940709275071
R2 score for z_hat_inv predicting z_spu: 0.7739629499381777
R2 score for z_inv predicting z_hat_inv: 0.11603974920945521
R2 score for z_spu predicting z_hat_inv: 0.049064970858340995
z_hat.shape: torch.Size([10000, 128]), z_hat_inv.shape: torch.Size([10000, 102]), z_inv.shape: torch.Size([10000, 2]), z_spu.shape: torch.Size([10000, 2]), z.shape: torch.Size([10000, 4])
z_hat.mean(): -0.0029534203931689262, z_hat.std: 0.37348514795303345
R2 score for z_hat predicting z: 0.9271091090198504
R2 score for z predicting z_hat: 0.24535708273606843
R2 score for z_hat_inv predicting z

R2 score for z_inv predicting z_hat_inv: 0.16238456152800884
R2 score for z_spu predicting z_hat_inv: 0.032926105499018685
z_hat.shape: torch.Size([10000, 128]), z_hat_inv.shape: torch.Size([10000, 102]), z_inv.shape: torch.Size([10000, 2]), z_spu.shape: torch.Size([10000, 2]), z.shape: torch.Size([10000, 4])
z_hat.mean(): -0.005993721541017294, z_hat.std: 0.32907918095588684
R2 score for z_hat predicting z: 0.9088038589204116
R2 score for z predicting z_hat: 0.27797410602905914
R2 score for z_hat_inv predicting z_inv: 0.907045620194552
R2 score for z_hat_inv predicting z_spu: 0.594137820430814
R2 score for z_inv predicting z_hat_inv: 0.16580505583151478
R2 score for z_spu predicting z_hat_inv: 0.02989792073325437
z_hat.shape: torch.Size([10000, 128]), z_hat_inv.shape: torch.Size([10000, 102]), z_inv.shape: torch.Size([10000, 2]), z_spu.shape: torch.Size([10000, 2]), z.shape: torch.Size([10000, 4])
z_hat.mean(): -0.006975686643272638, z_hat.std: 0.31021690368652344
R2 score for z_hat p

In [55]:
z_hat[4:50, :20]

tensor([[ 0.0329, -0.0770,  0.0573, -0.1214, -0.0241, -0.0164, -0.0309, -0.0233,
         -0.0517,  0.0196,  0.0190,  0.0594,  0.0259, -0.1605, -0.0486,  0.0383,
          0.0542,  0.0378,  0.0185,  0.0284],
        [ 0.0329, -0.0770,  0.0573, -0.1214, -0.0241, -0.0164, -0.0309, -0.0233,
         -0.0517,  0.0196,  0.0190,  0.0594,  0.0259, -0.1605, -0.0486,  0.0383,
          0.0542,  0.0378,  0.0185,  0.0284],
        [ 0.0329, -0.0770,  0.0573, -0.1214, -0.0241, -0.0164, -0.0309, -0.0233,
         -0.0517,  0.0196,  0.0190,  0.0594,  0.0259, -0.1605, -0.0486,  0.0383,
          0.0542,  0.0378,  0.0185,  0.0284],
        [ 0.0329, -0.0770,  0.0573, -0.1214, -0.0241, -0.0164, -0.0309, -0.0233,
         -0.0517,  0.0196,  0.0190,  0.0594,  0.0259, -0.1605, -0.0486,  0.0383,
          0.0542,  0.0378,  0.0185,  0.0284],
        [ 0.0329, -0.0770,  0.0573, -0.1214, -0.0241, -0.0164, -0.0309, -0.0233,
         -0.0517,  0.0196,  0.0190,  0.0594,  0.0259, -0.1605, -0.0486,  0.0383,
      

In [63]:
train_dataset = train_dataset_list[0]
val_dataset = valid_dataset_list[0]

In [64]:
z_hat_train = train_dataset["z_hat"]
z_hat_val = val_dataset["z_hat"]

In [65]:
print(z_hat_train[4:50, 100:])

tensor([[-5.9879e-02, -2.3539e-02, -5.8197e-05,  ..., -4.0739e-02,
          1.4632e-02,  5.9912e-02],
        [-6.0802e-02, -2.3427e-02, -3.1275e-03,  ..., -4.3685e-02,
          1.4666e-02,  6.0504e-02],
        [-6.1096e-02, -2.5066e-02, -4.6646e-03,  ..., -4.4718e-02,
          1.1903e-02,  5.8846e-02],
        ...,
        [-6.3649e-02, -2.3311e-02, -4.7670e-03,  ..., -4.5815e-02,
          1.5620e-02,  5.7651e-02],
        [-6.3734e-02, -2.4580e-02, -6.1810e-03,  ..., -4.1347e-02,
          1.6171e-02,  5.5425e-02],
        [-6.2430e-02, -2.0776e-02, -6.9927e-04,  ..., -4.1967e-02,
          1.7587e-02,  5.6644e-02]])


In [66]:
print(z_hat_val[4:50, 100:])

tensor([[-0.0286, -0.0258, -0.0100,  ..., -0.0577, -0.0638,  0.0496],
        [-0.0284, -0.0257, -0.0117,  ..., -0.0570, -0.0623,  0.0475],
        [-0.0282, -0.0256, -0.0112,  ..., -0.0581, -0.0624,  0.0482],
        ...,
        [-0.0281, -0.0257, -0.0093,  ..., -0.0592, -0.0640,  0.0473],
        [-0.0289, -0.0250, -0.0120,  ..., -0.0565, -0.0624,  0.0475],
        [-0.0286, -0.0250, -0.0108,  ..., -0.0581, -0.0632,  0.0472]])


In [68]:
encoded_img_dataset = torch.load("/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-05_07-21-05/encoded_img_md_balls_train.pt")

In [70]:
encoded_img_dataset["z_hat"][4:50, 100:]

tensor([[ 1.7712,  1.2271, -0.4686,  ..., -1.2296, -1.0679,  0.9576],
        [-0.1620,  1.2024,  1.3898,  ..., -0.3855,  1.0145, -0.3667],
        [-0.3807, -0.9126,  1.8747,  ...,  0.4598,  1.4371, -1.4684],
        ...,
        [-0.7341, -0.1005,  0.5609,  ...,  0.2023,  0.3206,  0.7329],
        [-2.2996, -2.1883, -1.0362,  ...,  0.8253,  0.6242,  0.0826],
        [-1.3353, -0.1981, -1.3465,  ...,  0.1698, -0.1596, -0.1901]])